version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    env_file:
    - .env

    ports:
      - 8080:8000
    
    environment:
    - API_REDIS_HOST=redis
    - API_POSTGRES_HOST=postgres
    - DATABASE_URL=postgresql://admin:qwerty@postgres:5432/api_bd

    command: [
      'uvicorn', 'main:app',
      '--host', '0.0.0.0',
      '--port', '8000',
      '--reload'
    ]

  redis:
    image: redis:latest
    hostname: 'redis'
    container_name: 'api_redis'
    build:
      context: .
      dockerfile: docker/redis/Dockerfile

    ports: 
      - 6379:6379
    environment:
      REDIS_PASSWORD: 12345678
      REDIS_REPLICATION_MODE: master
      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - ./_volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --requirepass 12345678 --include /usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:15.4-alpine
    hostname: 'postgres'
    container_name: 'api_postgres'
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "api_bd"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_USER: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./_volumes/postgres/var/run/postgresql:/var/run/postgresql
      - ./_volumes/postgres/log-directory:/var/lib/postgresql/data